const tournaments=[
{id:'brasil',name:'Copa CF Brasil',tag:'MATA-MATA • 16',players:12,max:16,entry:250,prize:'Troféu + 2.500 CF',time:'Hoje • 21:00'},
{id:'champions',name:'Champions CF',tag:'ELITE • 32',players:27,max:32,entry:500,prize:'Troféu + 8.000 CF',time:'Hoje • 22:30'},
{id:'flash',name:'Copa Relâmpago',tag:'MATA-MATA • 8',players:6,max:8,entry:100,prize:'1.000 CF',time:'Em 38 min'},
{id:'liga',name:'Liga Nacional CF',tag:'PONTOS CORRIDOS',players:41,max:64,entry:0,prize:'XP + Troféu',time:'Temporada aberta'},
{id:'nordeste',name:'Copa Nordeste CF',tag:'REGIONAL • 16',players:9,max:16,entry:200,prize:'2.000 CF',time:'Sáb • 20:00'},
{id:'rookie',name:'Rookie Cup',tag:'BRONZE/PRATA',players:18,max:32,entry:0,prize:'1.500 XP',time:'Dom • 18:00'}];
const ranking=[['01','NX','NeyX','SP • Lenda','4210'],['02','PS','PortoStar','BA • Elite','3980'],['03','RB','RafaPro','SP • Ouro II','2480'],['04','LK','Lukinhas','RJ • Ouro II','2314'],['05','JM','JotaMaster','MG • Ouro III','2190']];
const state=JSON.parse(localStorage.getItem('cf_state')||'{}');
state.coins=Number.isFinite(state.coins)?state.coins:1250; state.entries=state.entries||[];
state.room=state.room||{id:'CF-92841',myCheck:false,opCheck:false,result:null,opponentResult:null,status:'Pré-jogo'}; state.history=state.history||[]; state.disputes=state.disputes||[];
const save=()=>localStorage.setItem('cf_state',JSON.stringify(state));
const modal=document.querySelector('#modal'),content=document.querySelector('#modalContent'); const openModal=h=>{content.innerHTML=h;modal.showModal()}; document.querySelector('#modalClose').onclick=()=>modal.close();
function money(){document.querySelector('#walletBalance').textContent=state.coins.toLocaleString('pt-BR');document.querySelector('#coinStat').textContent=state.coins.toLocaleString('pt-BR')}
function renderTournaments(){const grid=document.querySelector('#tournamentGrid');grid.innerHTML='';tournaments.forEach(t=>{const joined=state.entries.includes(t.id);grid.insertAdjacentHTML('beforeend',`<article class="tournament-card"><span class="tag">${t.tag}</span><h3>${t.name}</h3><p>${t.time} • ${t.players}/${t.max} inscritos</p><div class="meta"><span>ENTRADA<br><b>${t.entry?t.entry+' CF':'GRÁTIS'}</b></span><span>PRÊMIO<br><b>${t.prize}</b></span></div><button class="${joined?'secondary':'primary'} full join-btn" data-id="${t.id}">${joined?'INSCRITO ✓':'PARTICIPAR'}</button></article>`)});}
function joinTournament(id){const t=tournaments.find(x=>x.id===id);if(!t||state.entries.includes(id))return;if(state.coins<t.entry){openModal(`<div class="modal-section"><span class="eyebrow">SALDO INSUFICIENTE</span><h2>Você precisa de ${t.entry} CF Coins</h2><p>Seu saldo atual é ${state.coins} CF. Compra com dinheiro real permanece desativada neste MVP até a camada financeira/regulatória ser aprovada.</p></div>`);return}openModal(`<div class="modal-section"><span class="eyebrow">CONFIRMAR INSCRIÇÃO</span><h2>${t.name}</h2><p>Entrada: <b>${t.entry?t.entry+' CF Coins':'Grátis'}</b><br>Formato: ${t.tag}<br>Prêmio: ${t.prize}</p><div class="proof-box">Ao confirmar, sua vaga entra na lista e o sistema poderá gerar automaticamente seu confronto quando a competição fechar.</div><button class="primary full" id="confirmEntry">CONFIRMAR VAGA</button></div>`);document.querySelector('#confirmEntry').onclick=()=>{state.coins-=t.entry;state.entries.push(id);t.players++;save();money();renderTournaments();modal.close();document.querySelector('#chave').scrollIntoView({behavior:'smooth'})}}
function renderBracket(){const games=[['RafaPro','PortoStar'],['NeyX','Bahia10'],['Lukinhas','GauchoX'],['JotaMaster','RecifeFC'],['Mago7','CariocaBR'],['LeoPro','MineiroX'],['Furia9','CearaKing'],['TitaMobile','AmazonFC']];document.querySelector('#bracket').innerHTML=games.map((g,i)=>`<div class="rank-row"><div class="rank-pos">${String(i+1).padStart(2,'0')}</div><div class="rank-info"><b>${g[0]} × ${g[1]}</b><small>${i===0?'Sua partida • Sala CF-92841':'Aguardando check-in'}</small></div><div class="rank-points">OITAVAS</div></div>`).join('')}
const rank=document.querySelector('#rankingList');ranking.forEach(r=>rank.insertAdjacentHTML('beforeend',`<div class="rank-row"><div class="rank-pos">${r[0]}</div><div class="rank-avatar">${r[1]}</div><div class="rank-info"><b>${r[2]}</b><small>${r[3]}</small></div><div class="rank-points">${r[4]} XP</div></div>`));
document.addEventListener('click',e=>{if(e.target.matches('.join-btn'))joinTournament(e.target.dataset.id);if(e.target.dataset.scroll)document.querySelector(e.target.dataset.scroll)?.scrollIntoView({behavior:'smooth'});if(e.target.dataset.adminDecision)resolveDispute(e.target.dataset.adminDecision)});
document.querySelector('#walletBtn').onclick=()=>openModal(`<div class="modal-section"><span class="eyebrow">ECONOMIA CF</span><h2>${state.coins.toLocaleString('pt-BR')} CF Coins</h2><p><b>XP</b> mede sua carreira e não é gasto.<br><b>CF Coins</b> são créditos virtuais usados no MVP para inscrições e recompensas.</p><div class="proof-box">Compra, saque e prêmio em dinheiro real não estão ativos. Essa camada deve ser separada e só habilitada após validação jurídica, KYC/idade, antifraude e integração de pagamento compatível.</div></div>`);
document.querySelector('#profileBtn').onclick=()=>openModal(`<div class="modal-section"><span class="eyebrow">PASSAPORTE COMPETITIVO</span><h2>RafaPro • Ouro II</h2><p>ID: <b>RAFA-88421</b><br>Campos do Jordão/SP<br>2.480 XP • 4 troféus</p><div class="meta"><span>VITÓRIAS<br><b>18</b></span><span>FAIR PLAY<br><b>100%</b></span><span>RANK BR<br><b>#3</b></span></div></div>`);
const myCheck=document.querySelector('#myCheck'),opCheck=document.querySelector('#opCheck'),roomStatus=document.querySelector('#roomStatus'),checkinBtn=document.querySelector('#checkinBtn');function renderRoom(){myCheck.textContent=state.room.myCheck?'Confirmado':'Aguardando';opCheck.textContent=state.room.opCheck?'Confirmado':'Aguardando';roomStatus.textContent=state.room.status;checkinBtn.textContent=state.room.myCheck?'CHECK-IN REALIZADO':'FAZER CHECK-IN';renderHistory();renderDisputes()};checkinBtn.onclick=()=>{state.room.myCheck=true;state.room.status='Aguardando adversário';save();renderRoom();setTimeout(()=>{state.room.opCheck=true;state.room.status='Liberada para jogar';save();renderRoom()},700)};
const proofInput=document.querySelector('#proofInput'),proofName=document.querySelector('#proofName');proofInput.onchange=()=>proofName.textContent=proofInput.files?.[0]?.name||'Selecionar imagem ou vídeo';document.querySelector('#submitResult').onclick=()=>{const v=document.querySelector('#validationBox');v.classList.remove('hidden');if(!state.room.myCheck||!state.room.opCheck){v.innerHTML='<b>Aguardando check-in dos dois jogadores.</b>';return}if(!proofInput.files?.length){v.innerHTML='<b>Anexe a prova do resultado.</b>';return}state.room.result={my:+document.querySelector('#myGoals').value,op:+document.querySelector('#opGoals').value,proofName:proofInput.files[0].name};state.room.status='Em validação';save();renderRoom();v.innerHTML=`<b>${state.room.result.my} × ${state.room.result.op} enviado.</b><br>Aguardando confirmação cruzada.`};
document.querySelector('#simulateOpponent').onclick=()=>{const v=document.querySelector('#validationBox');v.classList.remove('hidden');if(!state.room.result){v.innerHTML='<b>Envie seu resultado primeiro.</b>';return}state.room.opponentResult={my:state.room.result.op,op:state.room.result.my};state.room.status='Validada';upsertHistory('Validada',`${state.room.result.my} × ${state.room.result.op}`);save();renderRoom();v.innerHTML='<b>Resultado confirmado!</b><br>Você avançou no chaveamento e recebeu +30 XP no fluxo demonstrativo.'};
function upsertHistory(status,score){const f=state.history.find(h=>h.id===state.room.id),item={id:state.room.id,opponent:'PortoStar',city:'Porto Seguro/BA',score,status};f?Object.assign(f,item):state.history.unshift(item)}function renderHistory(){const l=document.querySelector('#historyList');document.querySelector('#historyCount').textContent=`${state.history.length} partida${state.history.length===1?'':'s'}`;l.innerHTML=state.history.length?state.history.map(h=>`<div class="rank-row"><div class="rank-avatar">CF</div><div class="rank-info"><b>${h.id} • ${h.score}</b><small>vs ${h.opponent} • ${h.city}</small></div><div class="rank-points">${h.status}</div></div>`).join(''):'<p>Nenhuma partida registrada.</p>'}function renderDisputes(){const p=state.disputes.filter(d=>d.status==='Pendente');document.querySelector('#adminCount').textContent=`${p.length} pendência${p.length===1?'':'s'}`;document.querySelector('#disputeList').innerHTML=p.length?p.map(d=>`<div class="proof-box"><b>${d.id}</b><br>${d.my} × ${d.op}<button class="primary full" data-admin-decision="validar">VALIDAR</button></div>`).join(''):'<div class="proof-box">Nenhuma disputa aberta.</div>'}function resolveDispute(){const d=state.disputes.find(x=>x.status==='Pendente');if(d)d.status='Resolvida';save();renderDisputes()}
money();renderTournaments();renderBracket();renderRoom();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});